#ifndef EMBERX_STATUS_H
#define EMBERX_STATUS_H

typedef enum EmberxStatus {
    EMBERX_SUCCESS = 0,
    EMBERX_IO_ERROR,
    EMBERX_YAML_SYNTAX_ERROR,
    EMBERX_INVALID_CONFIGURATION,
    EMBERX_INVALID_ARGUMENT,
    EMBERX_INVALID_DEVICE,
    EMBERX_INVALID_ALLOCATION,
    EMBERX_INVALID_STREAM,
    EMBERX_INVALID_EVENT,
    EMBERX_INVALID_COMPLETION,
    EMBERX_UNSUPPORTED_OPERATION,
    EMBERX_OUT_OF_MEMORY,
    EMBERX_EXECUTION_FAILED,
    EMBERX_NOT_INITIALIZED,
    EMBERX_ALREADY_INITIALIZED,
    EMBERX_INTERNAL_ERROR
} EmberxStatus;

#endif
